// packages/vue-ui/src/components/Checkbox.tsx
import {
  computed,
  defineComponent,
  inject,
  onMounted,
  provide,
  ref,
  watch,
  type InjectionKey,
  type PropType,
  type Ref,
} from "vue";

function isNodeDevelopment(): boolean {
  const proc = (globalThis as unknown as { process?: { env?: { NODE_ENV?: string } } })
    .process;
  return proc?.env?.NODE_ENV === "development";
}

type Orientation = "horizontal" | "vertical";

type CheckboxGroupProvided = {
  value: Ref<string[]>;
  setItemChecked: (itemValue: string, checked: boolean) => void;
  disabled: Ref<boolean>;
};

const CHECKBOX_GROUP_KEY: InjectionKey<CheckboxGroupProvided> = Symbol(
  "component-ai-checkbox-group",
);

function CheckIcon() {
  return (
    <svg width="10" height="10" viewBox="0 0 10 10" aria-hidden="true">
      <path
        d="M2 5.2 4.1 7.3 8 2.8"
        fill="none"
        stroke="currentColor"
        stroke-width="1.6"
        stroke-linecap="round"
        stroke-linejoin="round"
      />
    </svg>
  );
}

function MinusIcon() {
  return (
    <svg width="10" height="10" viewBox="0 0 10 10" aria-hidden="true">
      <path
        d="M2.5 5h5"
        fill="none"
        stroke="currentColor"
        stroke-width="1.6"
        stroke-linecap="round"
      />
    </svg>
  );
}

export const Checkbox = defineComponent({
  name: "Checkbox",
  props: {
    checked: { type: Boolean, default: undefined },
    defaultChecked: { type: Boolean, default: false },
    indeterminate: { type: Boolean, default: false },
    disabled: { type: Boolean, default: false },
    value: { type: String, default: undefined },
    class: { type: String, default: "" },
    label: { type: String, default: undefined },
  },
  emits: ["update:checked"],
  setup(props, { emit, slots }) {
    const group = inject(CHECKBOX_GROUP_KEY, null);
    const inputRef = ref<HTMLInputElement | null>(null);
    const inner = ref(props.defaultChecked);

    if (group && props.checked !== undefined && isNodeDevelopment()) {
      console.warn(
        "[Checkbox] `checked` is ignored inside CheckboxGroup; group value wins.",
      );
    }

    const inGroup = computed(
      () => group != null && props.value != null,
    );
    const checked = computed(() => {
      if (inGroup.value && group && props.value != null) {
        return group.value.value.includes(props.value);
      }
      return props.checked !== undefined ? props.checked : inner.value;
    });
    const isDisabled = computed(
      () => props.disabled || (group?.disabled.value ?? false),
    );
    const showIndeterminate = computed(
      () => props.indeterminate && !checked.value,
    );

    function syncIndeterminate() {
      if (inputRef.value) {
        inputRef.value.indeterminate = showIndeterminate.value;
      }
    }

    onMounted(syncIndeterminate);
    watch([showIndeterminate, checked], syncIndeterminate);

    function onChange(e: Event) {
      const next = (e.target as HTMLInputElement).checked;
      if (inGroup.value && group && props.value != null) {
        group.setItemChecked(props.value, next);
        return;
      }
      if (props.checked === undefined) inner.value = next;
      emit("update:checked", next);
    }

    return () => {
      const boxState =
        checked.value || showIndeterminate.value
          ? "border-sky-600 bg-sky-600"
          : "border-slate-300 bg-white";
      const labelText = slots.default?.() ?? props.label;

      return (
        <label
          class={`inline-flex items-center gap-2 text-sm text-slate-900 ${isDisabled.value ? "opacity-50" : ""} ${props.class}`.trim()}
        >
          <span class="relative inline-flex h-4 w-4 shrink-0 items-center justify-center">
            <input
              ref={inputRef}
              type="checkbox"
              class="peer absolute inset-0 z-10 m-0 h-4 w-4 cursor-pointer opacity-0 disabled:cursor-not-allowed"
              checked={checked.value}
              disabled={isDisabled.value}
              value={props.value}
              aria-checked={
                showIndeterminate.value ? "mixed" : checked.value
              }
              onChange={onChange}
            />
            <span
              aria-hidden="true"
              class={`pointer-events-none inline-flex h-4 w-4 items-center justify-center rounded border text-white peer-focus-visible:outline peer-focus-visible:outline-2 peer-focus-visible:outline-offset-2 peer-focus-visible:outline-sky-600 ${boxState}`}
            >
              {checked.value ? <CheckIcon /> : null}
              {showIndeterminate.value ? <MinusIcon /> : null}
            </span>
          </span>
          {labelText != null ? <span>{labelText}</span> : null}
        </label>
      );
    };
  },
});

export const CheckboxGroup = defineComponent({
  name: "CheckboxGroup",
  props: {
    modelValue: { type: Array as PropType<string[]>, default: undefined },
    defaultValue: {
      type: Array as PropType<string[]>,
      default: () => [],
    },
    disabled: { type: Boolean, default: false },
    orientation: {
      type: String as PropType<Orientation>,
      default: "vertical",
    },
    class: { type: String, default: "" },
    ariaLabel: { type: String, default: undefined },
    ariaLabelledby: { type: String, default: undefined },
  },
  emits: ["update:modelValue"],
  setup(props, { emit, slots, attrs }) {
    const inner = ref<string[]>([...(props.defaultValue ?? [])]);
    const isControlled = computed(() => props.modelValue !== undefined);
    const value = computed(() =>
      isControlled.value ? (props.modelValue as string[]) : inner.value,
    );
    const disabledRef = computed(() => props.disabled);

    function setItemChecked(itemValue: string, nextChecked: boolean) {
      const set = new Set(value.value);
      if (nextChecked) set.add(itemValue);
      else set.delete(itemValue);
      const next = [...set];
      if (!isControlled.value) inner.value = next;
      emit("update:modelValue", next);
    }

    provide(CHECKBOX_GROUP_KEY, {
      value: value as unknown as Ref<string[]>,
      setItemChecked,
      disabled: disabledRef as unknown as Ref<boolean>,
    });

    return () => {
      const layout =
        props.orientation === "horizontal"
          ? "flex flex-row flex-wrap gap-3"
          : "flex flex-col gap-2";
      const ariaLabel =
        props.ariaLabel ??
        (attrs["aria-label"] as string | undefined);
      const ariaLabelledby =
        props.ariaLabelledby ??
        (attrs["aria-labelledby"] as string | undefined);

      return (
        <div
          role="group"
          aria-label={ariaLabel}
          aria-labelledby={ariaLabelledby}
          class={`${layout} ${props.class}`.trim()}
        >
          {slots.default?.()}
        </div>
      );
    };
  },
});

// packages/react-ui/src/components/Checkbox.tsx
import {
  createContext,
  useContext,
  useEffect,
  useId,
  useRef,
  useState,
  type ChangeEvent,
  type InputHTMLAttributes,
  type ReactNode,
} from "react";

function isNodeDevelopment(): boolean {
  const proc = (globalThis as unknown as { process?: { env?: { NODE_ENV?: string } } })
    .process;
  return proc?.env?.NODE_ENV === "development";
}

type Orientation = "horizontal" | "vertical";

type CheckboxGroupContextValue = {
  value: string[];
  setItemChecked: (itemValue: string, checked: boolean) => void;
  disabled: boolean;
  name?: string;
};

const CheckboxGroupContext = createContext<CheckboxGroupContextValue | null>(
  null,
);

export type CheckboxProps = {
  checked?: boolean;
  defaultChecked?: boolean;
  indeterminate?: boolean;
  disabled?: boolean;
  value?: string;
  className?: string;
  children?: ReactNode;
  onCheckedChange?: (checked: boolean) => void;
} & Omit<
  InputHTMLAttributes<HTMLInputElement>,
  "type" | "checked" | "defaultChecked" | "onChange" | "value"
>;

function CheckIcon() {
  return (
    <svg width="10" height="10" viewBox="0 0 10 10" aria-hidden="true">
      <path
        d="M2 5.2 4.1 7.3 8 2.8"
        fill="none"
        stroke="currentColor"
        strokeWidth="1.6"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  );
}

function MinusIcon() {
  return (
    <svg width="10" height="10" viewBox="0 0 10 10" aria-hidden="true">
      <path
        d="M2.5 5h5"
        fill="none"
        stroke="currentColor"
        strokeWidth="1.6"
        strokeLinecap="round"
      />
    </svg>
  );
}

export function Checkbox({
  checked: checkedProp,
  defaultChecked = false,
  indeterminate = false,
  disabled = false,
  value,
  className = "",
  children,
  onCheckedChange,
  id: idProp,
  ...rest
}: CheckboxProps) {
  const group = useContext(CheckboxGroupContext);
  const reactId = useId();
  const id = idProp ?? `checkbox-${reactId}`;
  const inputRef = useRef<HTMLInputElement>(null);

  const [uncontrolled, setUncontrolled] = useState(defaultChecked);

  if (group && checkedProp !== undefined && isNodeDevelopment()) {
    console.warn(
      "[Checkbox] `checked` is ignored inside CheckboxGroup; group value wins.",
    );
  }

  const inGroup = group != null && value != null;
  const checked = inGroup
    ? group.value.includes(value)
    : checkedProp !== undefined
      ? checkedProp
      : uncontrolled;

  const isDisabled = disabled || (group?.disabled ?? false);

  useEffect(() => {
    if (inputRef.current) {
      inputRef.current.indeterminate = indeterminate && !checked;
    }
  }, [indeterminate, checked]);

  function handleChange(e: ChangeEvent<HTMLInputElement>) {
    const next = e.target.checked;
    if (inGroup && value != null) {
      group!.setItemChecked(value, next);
      return;
    }
    if (checkedProp === undefined) setUncontrolled(next);
    onCheckedChange?.(next);
  }

  const showChecked = checked;
  const showIndeterminate = indeterminate && !checked;
  const boxState = showChecked || showIndeterminate ? "border-sky-600 bg-sky-600" : "border-slate-300 bg-white";

  return (
    <label
      className={`inline-flex items-center gap-2 text-sm text-slate-900 ${isDisabled ? "opacity-50" : ""} ${className}`.trim()}
    >
      <span className="relative inline-flex h-4 w-4 shrink-0 items-center justify-center">
        <input
          {...rest}
          ref={inputRef}
          id={id}
          type="checkbox"
          className="peer absolute inset-0 z-10 m-0 h-4 w-4 cursor-pointer opacity-0 disabled:cursor-not-allowed"
          checked={checked}
          disabled={isDisabled}
          value={value}
          aria-checked={showIndeterminate ? "mixed" : checked}
          onChange={handleChange}
        />
        <span
          aria-hidden="true"
          className={`pointer-events-none inline-flex h-4 w-4 items-center justify-center rounded border text-white peer-focus-visible:outline peer-focus-visible:outline-2 peer-focus-visible:outline-offset-2 peer-focus-visible:outline-sky-600 ${boxState}`}
        >
          {showChecked ? <CheckIcon /> : null}
          {showIndeterminate ? <MinusIcon /> : null}
        </span>
      </span>
      {children != null && children !== false ? (
        <span>{children}</span>
      ) : null}
    </label>
  );
}

export type CheckboxGroupProps = {
  value?: string[];
  defaultValue?: string[];
  disabled?: boolean;
  orientation?: Orientation;
  className?: string;
  children?: ReactNode;
  onValueChange?: (value: string[]) => void;
  "aria-label"?: string;
  "aria-labelledby"?: string;
};

export function CheckboxGroup({
  value: valueProp,
  defaultValue = [],
  disabled = false,
  orientation = "vertical",
  className = "",
  children,
  onValueChange,
  "aria-label": ariaLabel,
  "aria-labelledby": ariaLabelledby,
}: CheckboxGroupProps) {
  const [uncontrolled, setUncontrolled] = useState(defaultValue);
  const isControlled = valueProp !== undefined;
  const value = isControlled ? valueProp! : uncontrolled;

  function setItemChecked(itemValue: string, nextChecked: boolean) {
    const set = new Set(value);
    if (nextChecked) set.add(itemValue);
    else set.delete(itemValue);
    const next = [...set];
    if (!isControlled) setUncontrolled(next);
    onValueChange?.(next);
  }

  const layout =
    orientation === "horizontal"
      ? "flex flex-row flex-wrap gap-3"
      : "flex flex-col gap-2";

  return (
    <CheckboxGroupContext.Provider
      value={{ value, setItemChecked, disabled }}
    >
      <div
        role="group"
        aria-label={ariaLabel}
        aria-labelledby={ariaLabelledby}
        className={`${layout} ${className}`.trim()}
      >
        {children}
      </div>
    </CheckboxGroupContext.Provider>
  );
}
