// packages/vue-ui/src/components/Radio.tsx
import {
  computed,
  defineComponent,
  inject,
  nextTick,
  onBeforeUnmount,
  provide,
  ref,
  useId,
  watch,
  type ComputedRef,
  type InjectionKey,
  type PropType,
} from "vue";

export type RadioOption = {
  label: string;
  value: string;
  disabled?: boolean;
};

export type RadioOrientation = "horizontal" | "vertical";

type RadioGroupProvided = {
  name: ComputedRef<string>;
  value: ComputedRef<string | undefined>;
  groupDisabled: ComputedRef<boolean>;
  setValue: (next: string) => void;
  registerSync: (fn: () => void) => void;
  unregisterSync: (fn: () => void) => void;
};

const RADIO_GROUP_KEY: InjectionKey<RadioGroupProvided> = Symbol(
  "component-ai-radio-group",
);

function useRadioGroupContext(component: string): RadioGroupProvided {
  const ctx = inject(RADIO_GROUP_KEY);
  if (!ctx) throw new Error(`${component} must be used inside <RadioGroup>`);
  return ctx;
}

export const Radio = defineComponent({
  name: "Radio",
  props: {
    value: { type: String, required: true },
    disabled: { type: Boolean, default: false },
    class: { type: String, default: "" },
  },
  setup(props, { slots }) {
    const ctx = useRadioGroupContext("Radio");
    const inputRef = ref<HTMLInputElement | null>(null);

    function syncCheckedFromContext() {
      if (inputRef.value) {
        inputRef.value.checked = ctx.value.value === props.value;
      }
    }

    ctx.registerSync(syncCheckedFromContext);
    watch(() => ctx.value.value, syncCheckedFromContext);
    onBeforeUnmount(() => ctx.unregisterSync(syncCheckedFromContext));

    function handleChange() {
      const disabled = ctx.groupDisabled.value || props.disabled;
      if (disabled) return;
      ctx.setValue(props.value);
    }

    return () => {
      const checked = ctx.value.value === props.value;
      const disabled = ctx.groupDisabled.value || props.disabled;
      const wrapperCls =
        `inline-flex items-center gap-2 text-sm text-slate-800 ${
          disabled ? "cursor-not-allowed opacity-50" : "cursor-pointer"
        } ${props.class}`.trim();
      const inputCls =
        "h-4 w-4 shrink-0 border-slate-300 text-sky-600 accent-sky-600 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-sky-600 disabled:cursor-not-allowed";

      return (
        <label class={wrapperCls}>
          <input
            ref={inputRef}
            type="radio"
            name={ctx.name.value}
            value={props.value}
            checked={checked}
            disabled={disabled}
            class={inputCls}
            onChange={handleChange}
          />
          {slots.default?.()}
        </label>
      );
    };
  },
});

export const RadioGroup = defineComponent({
  name: "RadioGroup",
  props: {
    modelValue: { type: String as PropType<string | undefined>, default: undefined },
    defaultModelValue: {
      type: String as PropType<string | undefined>,
      default: undefined,
    },
    options: {
      type: Array as PropType<RadioOption[]>,
      default: undefined,
    },
    orientation: {
      type: String as PropType<RadioOrientation>,
      default: "horizontal",
    },
    disabled: { type: Boolean, default: false },
    name: { type: String, default: undefined },
    id: { type: String, default: undefined },
    class: { type: String, default: "" },
  },
  emits: {
    "update:modelValue": (_value: string) => true,
  },
  setup(props, { emit, slots }) {
    const generatedName = useId().replace(/:/g, "");
    const isControlled = () => props.modelValue !== undefined;
    const internal = ref<string | undefined>(props.defaultModelValue);
    const syncFns = new Set<() => void>();

    const nameRef = computed(() => props.name ?? generatedName);
    const valueRef = computed(() =>
      isControlled() ? props.modelValue : internal.value,
    );
    const groupDisabled = computed(() => props.disabled);

    function syncAll() {
      for (const fn of syncFns) fn();
    }

    function setValue(next: string) {
      if (props.disabled) return;
      if (!isControlled()) internal.value = next;
      emit("update:modelValue", next);
      // 受控：父未更新 prop 时，把所有 radio DOM 拉回组当前值
      if (isControlled()) {
        nextTick(syncAll);
      }
    }

    provide(RADIO_GROUP_KEY, {
      name: nameRef,
      value: valueRef,
      groupDisabled,
      setValue,
      registerSync: (fn) => {
        syncFns.add(fn);
      },
      unregisterSync: (fn) => {
        syncFns.delete(fn);
      },
    });

    return () => {
      const orientationCls =
        props.orientation === "vertical"
          ? "inline-flex flex-col gap-2"
          : "inline-flex flex-row flex-wrap items-center gap-4";

      return (
        <div
          id={props.id}
          role="radiogroup"
          class={`${orientationCls} ${props.class}`.trim()}
        >
          {props.options?.map((opt) => (
            <Radio
              key={opt.value}
              value={opt.value}
              disabled={opt.disabled}
            >
              {opt.label}
            </Radio>
          ))}
          {slots.default?.()}
        </div>
      );
    };
  },
});

// packages/react-ui/src/components/Radio.tsx
import {
  createContext,
  useContext,
  useId,
  useState,
  type ChangeEvent,
  type ReactNode,
} from "react";

export type RadioOption = {
  label: string;
  value: string;
  disabled?: boolean;
};

export type RadioGroupProps = {
  value?: string;
  defaultValue?: string;
  onChange?: (value: string) => void;
  options?: RadioOption[];
  orientation?: "horizontal" | "vertical";
  disabled?: boolean;
  name?: string;
  id?: string;
  className?: string;
  children?: ReactNode;
  "aria-labelledby"?: string;
};

export type RadioProps = {
  value: string;
  disabled?: boolean;
  children?: ReactNode;
  className?: string;
};

type RadioGroupContextValue = {
  name: string;
  value: string;
  disabled: boolean;
  onChange: (value: string) => void;
};

const RadioGroupContext = createContext<RadioGroupContextValue | null>(null);

export function RadioGroup({
  value: valueProp,
  defaultValue = "",
  onChange,
  options,
  orientation = "horizontal",
  disabled = false,
  name: nameProp,
  id,
  className = "",
  children,
  "aria-labelledby": ariaLabelledby,
}: RadioGroupProps) {
  const autoId = useId();
  const name = nameProp ?? `radio-${autoId}`;
  const [uncontrolled, setUncontrolled] = useState(defaultValue);
  const value = valueProp ?? uncontrolled;

  function handleChange(next: string) {
    if (valueProp === undefined) setUncontrolled(next);
    onChange?.(next);
  }

  const orientationCls =
    orientation === "vertical" ? "flex flex-col gap-2" : "flex gap-4";

  const rootCls = `${orientationCls} ${className}`.trim();

  return (
    <RadioGroupContext.Provider
      value={{ name, value, disabled, onChange: handleChange }}
    >
      <div
        role="radiogroup"
        id={id}
        aria-labelledby={ariaLabelledby}
        className={rootCls}
      >
        {options?.map((opt) => (
          <Radio key={opt.value} value={opt.value} disabled={opt.disabled}>
            {opt.label}
          </Radio>
        ))}
        {children}
      </div>
    </RadioGroupContext.Provider>
  );
}

export function Radio({
  value,
  disabled = false,
  children,
  className = "",
}: RadioProps) {
  const ctx = useContext(RadioGroupContext);
  if (!ctx) {
    throw new Error("Radio must be used within a RadioGroup");
  }
  const group = ctx;

  const isDisabled = disabled || group.disabled;
  const checked = group.value === value;

  function handleChange(e: ChangeEvent<HTMLInputElement>) {
    if (e.target.checked) group.onChange(value);
  }

  const wrapperCls =
    `inline-flex items-center gap-2 text-sm text-slate-800 ${
      isDisabled ? "cursor-not-allowed opacity-50" : "cursor-pointer"
    } ${className}`.trim();

  const inputCls =
    "h-4 w-4 shrink-0 border-slate-300 text-sky-600 accent-sky-600 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-sky-600 disabled:cursor-not-allowed";

  return (
    <label className={wrapperCls}>
      <input
        type="radio"
        name={group.name}
        value={value}
        checked={checked}
        disabled={isDisabled}
        className={inputCls}
        onChange={handleChange}
      />
      {children}
    </label>
  );
}
