// packages/vue-ui/src/components/VirtualGrid.tsx
import {
  clearKeys,
  computeVirtualWindow,
  isAllSelected,
  isIndeterminate,
  selectAllKeys,
  slicePage,
  toggleKey,
  type GridColumn,
} from "@component-ai/grid-core";
import { computed, defineComponent, ref, watch, type PropType } from "vue";
import { Checkbox } from "./Checkbox";
import { Pagination } from "./Pagination";

export type VirtualGridColumn = GridColumn;

const ROW_NUMBER_WIDTH = 48;
const SELECTION_WIDTH = 40;

function isNodeDevelopment(): boolean {
  const proc = (globalThis as unknown as { process?: { env?: { NODE_ENV?: string } } })
    .process;
  return proc?.env?.NODE_ENV === "development";
}

function toCssHeight(height: number | string): string {
  return typeof height === "number" ? `${height}px` : height;
}

export const VirtualGrid = defineComponent({
  name: "VirtualGrid",
  props: {
    columns: { type: Array as PropType<VirtualGridColumn[]>, required: true },
    data: {
      type: Array as PropType<Record<string, unknown>[]>,
      required: true,
    },
    idField: { type: String, default: "id" },
    rowHeight: { type: Number, default: 36 },
    height: {
      type: [Number, String] as PropType<number | string | undefined>,
      default: undefined,
    },
    virtual: { type: Boolean, default: false },
    overscan: { type: Number, default: 4 },
    bordered: { type: Boolean, default: true },
    stripe: { type: Boolean, default: false },
    showRowNumber: { type: Boolean, default: false },
    emptyText: { type: String, default: "暂无数据" },
    class: { type: String, default: "" },
    selectable: { type: Boolean, default: false },
    multiple: { type: Boolean, default: true },
    selectedKeys: {
      type: Array as PropType<string[] | undefined>,
      default: undefined,
    },
    defaultSelectedKeys: {
      type: Array as PropType<string[]>,
      default: () => [],
    },
    showSelectAll: { type: Boolean, default: true },
    pagination: { type: Boolean, default: false },
    page: { type: Number, default: undefined },
    defaultPage: { type: Number, default: 1 },
    pageSize: { type: Number, default: undefined },
    defaultPageSize: { type: Number, default: 10 },
    pageSizeOptions: {
      type: Array as PropType<number[] | undefined>,
      default: undefined,
    },
  },
  emits: {
    "update:selectedKeys": (_keys: string[]) => true,
    "update:page": (_page: number) => true,
    "update:pageSize": (_pageSize: number) => true,
  },
  setup(props, { emit, slots }) {
    const scrollTop = ref(0);
    const uncontrolledSelectedKeys = ref<string[]>(props.defaultSelectedKeys);
    const uncontrolledPage = ref(props.defaultPage);
    const uncontrolledPageSize = ref(props.defaultPageSize);

    const selectedKeys = computed(
      () => props.selectedKeys ?? uncontrolledSelectedKeys.value,
    );
    const page = computed(() => props.page ?? uncontrolledPage.value);
    const pageSize = computed(() => props.pageSize ?? uncontrolledPageSize.value);

    function commitSelectedKeys(next: string[]) {
      if (props.selectedKeys === undefined) uncontrolledSelectedKeys.value = next;
      emit("update:selectedKeys", next);
    }

    function setPage(next: number) {
      if (props.page === undefined) uncontrolledPage.value = next;
      emit("update:page", next);
    }

    function setPageSize(next: number) {
      if (props.pageSize === undefined) uncontrolledPageSize.value = next;
      emit("update:pageSize", next);
      if (props.page === undefined) uncontrolledPage.value = 1;
      emit("update:page", 1);
    }

    watch(page, () => {
      scrollTop.value = 0;
    });

    const visibleColumns = computed(() =>
      props.columns.filter((c) => !c.hidden),
    );

    const pagedRows = computed(() =>
      props.pagination
        ? slicePage(props.data, {
            pageIndex: page.value,
            pageSize: pageSize.value,
            total: props.data.length,
          })
        : props.data,
    );

    function rowKey(
      row: Record<string, unknown>,
      absoluteIndex: number,
    ): string {
      const v = row[props.idField];
      return v !== undefined && v !== null ? String(v) : String(absoluteIndex);
    }

    const allKeys = computed(() =>
      pagedRows.value.map((row, i) => rowKey(row, i)),
    );

    const canVirtualize = computed(
      () => props.virtual && typeof props.height === "number",
    );

    if (
      props.virtual &&
      typeof props.height !== "number" &&
      isNodeDevelopment()
    ) {
      console.warn(
        "VirtualGrid: `virtual` requires a numeric `height` prop; falling back to non-virtual rendering.",
      );
    }

    const win = computed(() =>
      computeVirtualWindow({
        enabled: canVirtualize.value,
        rowCount: pagedRows.value.length,
        rowHeight: props.rowHeight,
        scrollTop: scrollTop.value,
        viewportHeight: canVirtualize.value ? (props.height as number) : 0,
        overscan: props.overscan,
      }),
    );

    const gridTemplateColumns = computed(() => {
      const widths = visibleColumns.value.map((c) =>
        c.width ? `${c.width}px` : "1fr",
      );
      const prefixed = [
        ...(props.selectable ? [`${SELECTION_WIDTH}px`] : []),
        ...(props.showRowNumber ? [`${ROW_NUMBER_WIDTH}px`] : []),
        ...widths,
      ];
      return prefixed.join(" ");
    });

    function onScroll(e: Event) {
      if (canVirtualize.value) {
        scrollTop.value = (e.currentTarget as HTMLElement).scrollTop;
      }
    }

    const cellBase = () =>
      `flex items-center overflow-hidden px-3 py-2 truncate ${
        props.bordered ? "border-b border-slate-200" : ""
      }`;

    function renderRow(row: Record<string, unknown>, absoluteIndex: number) {
      const key = rowKey(row, absoluteIndex);
      return (
        <div
          key={key}
          role="row"
          aria-rowindex={absoluteIndex + 2}
          style={{
            display: "grid",
            gridTemplateColumns: gridTemplateColumns.value,
            height: `${props.rowHeight}px`,
          }}
          class={props.stripe && absoluteIndex % 2 === 1 ? "bg-slate-50" : ""}
        >
          {props.selectable ? (
            <div role="cell" class={cellBase()}>
              <Checkbox
                modelValue={selectedKeys.value.includes(key)}
                onUpdate:modelValue={() =>
                  commitSelectedKeys(
                    toggleKey(selectedKeys.value, key, props.multiple),
                  )
                }
              >
                <span class="sr-only">选择第 {absoluteIndex + 1} 行</span>
              </Checkbox>
            </div>
          ) : null}
          {props.showRowNumber ? (
            <div role="cell" class={cellBase()}>
              {absoluteIndex + 1}
            </div>
          ) : null}
          {visibleColumns.value.map((col) => (
            <div key={col.field} role="cell" class={cellBase()}>
              {String(row[col.field] ?? "")}
            </div>
          ))}
        </div>
      );
    }

    return () => {
      const rootCls =
        `inline-block w-full overflow-hidden rounded-lg text-sm text-slate-800 ${
          props.bordered ? "border border-slate-200" : ""
        } ${props.class}`.trim();
      const allSelected = isAllSelected(selectedKeys.value, allKeys.value);
      const partiallySelected = isIndeterminate(
        selectedKeys.value,
        allKeys.value,
      );

      return (
        <div
          class={rootCls}
          role="table"
          aria-rowcount={pagedRows.value.length + 1}
        >
          <div
            role="row"
            aria-rowindex={1}
            style={{
              display: "grid",
              gridTemplateColumns: gridTemplateColumns.value,
            }}
            class="bg-slate-50 font-medium"
          >
            {props.selectable ? (
              <div role="columnheader" class={cellBase()}>
                {props.multiple && props.showSelectAll ? (
                  <Checkbox
                    modelValue={allSelected}
                    indeterminate={partiallySelected}
                    onUpdate:modelValue={() =>
                      commitSelectedKeys(
                        allSelected
                          ? clearKeys()
                          : selectAllKeys(allKeys.value),
                      )
                    }
                  >
                    <span class="sr-only">全选</span>
                  </Checkbox>
                ) : null}
              </div>
            ) : null}
            {props.showRowNumber ? (
              <div role="columnheader" class={cellBase()} aria-label="序号">
                #
              </div>
            ) : null}
            {visibleColumns.value.map((col) => (
              <div key={col.field} role="columnheader" class={cellBase()}>
                {col.title}
              </div>
            ))}
          </div>
          <div
            role="rowgroup"
            class="relative overflow-y-auto"
            style={
              props.height !== undefined
                ? { height: toCssHeight(props.height) }
                : undefined
            }
            onScroll={onScroll}
          >
            {pagedRows.value.length === 0 ? (
              <div class="px-3 py-6 text-center text-slate-400">
                {slots.empty?.() ?? props.emptyText}
              </div>
            ) : canVirtualize.value ? (
              <div
                style={{
                  height: `${win.value.totalHeight}px`,
                  position: "relative",
                }}
              >
                <div style={{ transform: `translateY(${win.value.offsetY}px)` }}>
                  {pagedRows.value
                    .slice(win.value.startIndex, win.value.endIndex)
                    .map((row, i) => renderRow(row, win.value.startIndex + i))}
                </div>
              </div>
            ) : (
              pagedRows.value.map((row, absoluteIndex) =>
                renderRow(row, absoluteIndex),
              )
            )}
          </div>
          {props.pagination ? (
            <div
              class={`flex justify-end p-2 ${
                props.bordered ? "border-t border-slate-200" : ""
              }`}
            >
              <Pagination
                total={props.data.length}
                page={page.value}
                pageSize={pageSize.value}
                pageSizeOptions={props.pageSizeOptions}
                onUpdate:page={setPage}
                onUpdate:pageSize={setPageSize}
              />
            </div>
          ) : null}
        </div>
      );
    };
  },
});

// packages/react-ui/src/components/VirtualGrid.tsx
import {
  clearKeys,
  computeVirtualWindow,
  isAllSelected,
  isIndeterminate,
  selectAllKeys,
  slicePage,
  toggleKey,
  type GridColumn,
} from "@component-ai/grid-core";
import { Checkbox } from "./Checkbox";
import { Pagination } from "./Pagination";
import {
  useCallback,
  useEffect,
  useMemo,
  useRef,
  useState,
  type MouseEvent,
  type ReactNode,
} from "react";

function isNodeDevelopment(): boolean {
  const proc = (
    globalThis as unknown as { process?: { env?: { NODE_ENV?: string } } }
  ).process;
  return proc?.env?.NODE_ENV === "development";
}

export type VirtualGridColumn<T = Record<string, unknown>> = GridColumn & {
  render?: (ctx: {
    row: T;
    column: VirtualGridColumn<T>;
    rowIndex: number;
  }) => ReactNode;
  renderHeader?: (column: VirtualGridColumn<T>) => ReactNode;
};

export type VirtualGridProps<T = Record<string, unknown>> = {
  data: T[];
  columns: VirtualGridColumn<T>[];
  idField?: string;
  showHeader?: boolean;
  bordered?: boolean;
  stripe?: boolean;
  showRowNumber?: boolean;
  rowHeight?: number;
  enableVirtual?: boolean;
  className?: string;
  emptyText?: string;
  renderCell?: (ctx: {
    row: T;
    column: VirtualGridColumn<T>;
    rowIndex: number;
  }) => ReactNode;
  renderHeader?: (column: VirtualGridColumn<T>) => ReactNode;
  onRowClick?: (row: T, rowIndex: number, event: MouseEvent) => void;
  selectionMode?: "none" | "single" | "multiple";
  selectedKeys?: string[];
  defaultSelectedKeys?: string[];
  onSelectedKeysChange?: (keys: string[]) => void;
  pagination?: boolean;
  paginationMode?: "local" | "remote";
  page?: number;
  defaultPage?: number;
  onPageChange?: (page: number) => void;
  pageSize?: number;
  defaultPageSize?: number;
  onPageSizeChange?: (pageSize: number) => void;
  total?: number;
  pageSizeOptions?: number[];
};

function getVisibleColumns<T>(
  columns: VirtualGridColumn<T>[],
): VirtualGridColumn<T>[] {
  return columns.filter((col) => {
    if (col.children?.length && isNodeDevelopment()) {
      console.warn(
        `[VirtualGrid] column "${col.field}" has children; P0 ignores nested headers`,
      );
    }
    return !col.hidden;
  });
}

function rowKey<T extends Record<string, unknown>>(
  row: T,
  index: number,
  idField: string,
): string {
  const raw = row[idField];
  if (raw === undefined || raw === null || raw === "") {
    if (isNodeDevelopment()) {
      console.warn(`[VirtualGrid] missing idField "${idField}" at row ${index}`);
    }
    return `row-${index}`;
  }
  return String(raw);
}

export function VirtualGrid<
  T extends Record<string, unknown> = Record<string, unknown>,
>({
  data,
  columns,
  idField = "id",
  showHeader = true,
  bordered = true,
  stripe = false,
  showRowNumber = true,
  rowHeight = 36,
  enableVirtual = false,
  className = "",
  emptyText = "暂无数据",
  renderCell,
  renderHeader,
  onRowClick,
  selectionMode = "none",
  selectedKeys: selectedKeysProp,
  defaultSelectedKeys = [],
  onSelectedKeysChange,
  pagination = false,
  paginationMode = "local",
  page: pageProp,
  defaultPage = 1,
  onPageChange,
  pageSize: pageSizeProp,
  defaultPageSize = 10,
  onPageSizeChange,
  total: totalProp,
  pageSizeOptions,
}: VirtualGridProps<T>) {
  const visibleColumns = useMemo(() => getVisibleColumns(columns), [columns]);
  const bodyRef = useRef<HTMLDivElement>(null);
  const [scrollTop, setScrollTop] = useState(0);
  const [viewportHeight, setViewportHeight] = useState(0);
  const [innerKeys, setInnerKeys] = useState(defaultSelectedKeys);
  const [innerPage, setInnerPage] = useState(defaultPage);
  const [innerSize, setInnerSize] = useState(defaultPageSize);

  const selectedKeys = selectedKeysProp !== undefined ? selectedKeysProp : innerKeys;
  const page = pageProp !== undefined ? pageProp : innerPage;
  const pageSize = pageSizeProp !== undefined ? pageSizeProp : innerSize;

  const showSelection = selectionMode !== "none";
  const multiple = selectionMode === "multiple";

  const paginationTotal =
    pagination && paginationMode === "remote"
      ? (totalProp ?? data.length)
      : data.length;

  const measure = useCallback(() => {
    const el = bodyRef.current;
    if (!el) return;
    setViewportHeight(el.clientHeight);
  }, []);

  useEffect(() => {
    measure();
    const el = bodyRef.current;
    if (!el || typeof ResizeObserver === "undefined") return;
    const ro = new ResizeObserver(() => measure());
    ro.observe(el);
    return () => ro.disconnect();
  }, [measure]);

  useEffect(() => {
    if (
      pagination &&
      paginationMode === "remote" &&
      totalProp === undefined &&
      isNodeDevelopment()
    ) {
      console.warn(
        "[VirtualGrid] paginationMode=remote without `total`; falling back to data.length",
      );
    }
  }, [pagination, paginationMode, totalProp, data.length]);

  const pageRows = useMemo(() => {
    if (!pagination) return data;
    if (paginationMode === "remote") return data;
    return slicePage(data, {
      pageIndex: page,
      pageSize,
      total: data.length,
    });
  }, [pagination, paginationMode, data, page, pageSize]);

  const scopeKeys = useMemo(
    () => data.map((row, index) => rowKey(row, index, idField)),
    [data, idField],
  );

  function setSelectedKeys(next: string[]) {
    if (selectedKeysProp === undefined) setInnerKeys(next);
    onSelectedKeysChange?.(next);
  }

  function setPage(next: number) {
    if (pageProp === undefined) setInnerPage(next);
    onPageChange?.(next);
  }

  function setPageSize(next: number) {
    if (pageSizeProp === undefined) setInnerSize(next);
    onPageSizeChange?.(next);
    if (pageProp === undefined) setInnerPage(1);
    onPageChange?.(1);
  }

  function onToggleRow(key: string) {
    setSelectedKeys(toggleKey(selectedKeys, key, multiple));
  }

  function onToggleAll() {
    if (isAllSelected(selectedKeys, scopeKeys) || isIndeterminate(selectedKeys, scopeKeys)) {
      setSelectedKeys(clearKeys());
    } else {
      setSelectedKeys(selectAllKeys(scopeKeys));
    }
  }

  const windowResult = useMemo(
    () =>
      computeVirtualWindow({
        enabled: enableVirtual,
        rowCount: pageRows.length,
        rowHeight,
        scrollTop,
        viewportHeight: Math.max(viewportHeight, 1),
        overscan: 2,
      }),
    [enableVirtual, pageRows.length, rowHeight, scrollTop, viewportHeight],
  );

  const start = windowResult.startIndex;
  const end = windowResult.endIndex;
  const slice = pageRows.slice(start, end);

  function cellContent(row: T, column: VirtualGridColumn<T>, rowIndex: number) {
    if (column.render) return column.render({ row, column, rowIndex });
    if (renderCell) return renderCell({ row, column, rowIndex });
    const v = row[column.field as keyof T];
    return v == null ? "" : String(v);
  }

  function headerContent(column: VirtualGridColumn<T>) {
    if (column.renderHeader) return column.renderHeader(column);
    if (renderHeader) return renderHeader(column);
    return column.title;
  }

  const borderCls = bordered ? "border border-slate-200" : "border-0";
  const gridCls =
    `flex h-full min-h-0 w-full flex-col overflow-hidden rounded-lg bg-white text-sm text-slate-900 ${borderCls} ${className}`.trim();
  const outerCls =
    `flex h-full min-h-0 w-full flex-col text-sm text-slate-900 ${className}`.trim();
  const cardCls =
    `flex min-h-0 flex-1 flex-col overflow-hidden rounded-lg bg-white ${borderCls}`.trim();

  return (
    <div
      data-testid="virtual-grid"
      className={pagination ? outerCls : gridCls}
      role="grid"
    >
      <div className={pagination ? cardCls : "contents"}>
        {showHeader ? (
          <div
            className="flex shrink-0 border-b border-slate-200 bg-slate-50"
            role="row"
          >
            {showSelection ? (
              <div
                className="flex w-12 shrink-0 items-center justify-center border-r border-slate-200"
                role="columnheader"
                style={{ height: rowHeight }}
              >
                {multiple ? (
                  <Checkbox
                    aria-label="全选"
                    checked={isAllSelected(selectedKeys, scopeKeys)}
                    indeterminate={isIndeterminate(selectedKeys, scopeKeys)}
                    onCheckedChange={() => onToggleAll()}
                  />
                ) : null}
              </div>
            ) : null}
            {showRowNumber ? (
              <div
                className="flex w-14 shrink-0 items-center justify-center border-r border-slate-200 px-1 font-medium text-slate-600"
                style={{ height: rowHeight }}
                role="columnheader"
              >
                #
              </div>
            ) : null}
            {visibleColumns.map((col) => (
              <div
                key={col.field}
                className="flex shrink-0 items-center border-r border-slate-200 px-3 font-medium text-slate-700 last:border-r-0"
                style={{
                  width: col.width ?? 120,
                  height: rowHeight,
                }}
                role="columnheader"
              >
                {headerContent(col)}
              </div>
            ))}
          </div>
        ) : null}

        <div
          ref={bodyRef}
          data-testid="virtual-grid-body"
          className="relative min-h-0 flex-1 overflow-auto"
          onScroll={(e) => {
            setScrollTop(e.currentTarget.scrollTop);
            setViewportHeight(e.currentTarget.clientHeight);
          }}
        >
          {data.length === 0 ? (
            <div className="flex h-full min-h-24 items-center justify-center text-slate-500">
              {emptyText}
            </div>
          ) : (
            <div
              className="relative w-full"
              style={{
                height: enableVirtual
                  ? windowResult.totalHeight
                  : pageRows.length * rowHeight,
              }}
            >
              <div
                className="absolute left-0 right-0"
                style={{
                  transform: enableVirtual
                    ? `translateY(${windowResult.offsetY}px)`
                    : undefined,
                  top: enableVirtual ? 0 : undefined,
                }}
              >
                {slice.map((row, i) => {
                  const rowIndex = start + i;
                  const key = rowKey(row, rowIndex, idField);
                  const displayIndex =
                    (pagination ? (page - 1) * pageSize : 0) + rowIndex + 1;
                  const zebra =
                    stripe && rowIndex % 2 === 1 ? "bg-slate-50" : "bg-white";
                  return (
                    <div
                      key={key}
                      role="row"
                      data-row-index={rowIndex}
                      className={`flex border-b border-slate-100 ${zebra} hover:bg-sky-50/60`}
                      style={{ height: rowHeight }}
                      onClick={(e) => onRowClick?.(row, rowIndex, e)}
                    >
                      {showSelection ? (
                        <div
                          className="flex w-12 shrink-0 items-center justify-center border-r border-slate-100"
                          role="gridcell"
                          onClick={(e) => e.stopPropagation()}
                        >
                          <Checkbox
                            aria-label={`选择行 ${key}`}
                            checked={selectedKeys.includes(key)}
                            onCheckedChange={() => onToggleRow(key)}
                          />
                        </div>
                      ) : null}
                      {showRowNumber ? (
                        <div
                          className="flex w-14 shrink-0 items-center justify-center border-r border-slate-100 text-slate-500"
                          role="gridcell"
                        >
                          {displayIndex}
                        </div>
                      ) : null}
                      {visibleColumns.map((col) => (
                        <div
                          key={col.field}
                          className="flex shrink-0 items-center overflow-hidden border-r border-slate-100 px-3 text-ellipsis whitespace-nowrap last:border-r-0"
                          style={{ width: col.width ?? 120 }}
                          role="gridcell"
                        >
                          {cellContent(row, col, rowIndex)}
                        </div>
                      ))}
                    </div>
                  );
                })}
              </div>
            </div>
          )}
        </div>
      </div>
      {pagination ? (
        <div data-testid="virtual-grid-pagination" className="mt-2 shrink-0">
          <Pagination
            total={paginationTotal}
            page={page}
            pageSize={pageSize}
            pageSizeOptions={pageSizeOptions}
            onPageChange={setPage}
            onPageSizeChange={setPageSize}
          />
        </div>
      ) : null}
    </div>
  );
}
